name: Continuous Deployment

# on:
#   push:
#     branches: [main]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
    
#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '21'

#     - name: Install dependencies and Build
#       run: npm ci
#       run: npm run build

#     - name: Deploy-pages
#       - uses: actions/configure-pages@v3
#       - uses: actions/deploy-pages@v2

on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    uses: ./.github/workflows/CI.yml
    with:
      upload-pages-artifact: true
  deploy-to-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build-and-test
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
        id: deployment