# name: Continuous-Integration

# #trigger workflow
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# #jobs and tests
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
    
#     #sets up Node.js
#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '21' 

#     - name: Install dependencies
#       run: npm ci
#     - name: Run tests
#       run: npm test

#     - name: Start application
#       run: npm start &
          
#     - name: Cypress test
#       run: npm run cy:run

name: Continuous Integration
on:
  workflow_call:
    inputs:
      upload-pages-artifact:
        type: boolean
        required: false
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm start &
      - run: npm run cy:run
      - uses: actions/upload-artifact@v3
      #   with:
      #     name: e2e-videos
      #     path: cypress/videos/
      # - if: ${{ inputs.upload-pages-artifact }}
      #   uses: actions/upload-pages-artifact@v1
        with:
          path: build/