name: Continuous-Integration

#trigger workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

#jobs and tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    #sets up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21' 

    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test

    - name: Start application
      run: npm start &
          
    - name: Cypress test
      run: npm run cy:run